package gui;

import model.Memory;

import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hoan toan hanh phuc
 */
public class Calculator extends javax.swing.JFrame {
 
    private Memory m = null;
    private final DecimalFormat defaultFormat = new DecimalFormat("#.#######");
    private double result = 0;
    private static String operation = "add";
    public boolean check = true;
    
    /**
     * Creates new form ControlCalculator
     */
    public Calculator() {
        initComponents();       
        defaultFormat.setDecimalFormatSymbols(DecimalFormatSymbols.getInstance(Locale.US));
        txtDisplay.setText("0");
    }

    public double getNumber() {
        return Double.parseDouble(txtDisplay.getText());
    }
  
    public void setTextFormat(double f) {
        txtDisplay.setText(defaultFormat.format(f));
    }
  

    public void actionPerformed(ActionEvent e) {
        String str = e.getActionCommand();
        if (check) {
            result = getNumber();
            txtDisplay.setText(str);
            check = false;
        } else {
//            if (txtDisplay.getText().equals("-0")) {
//                txtDisplay.setText("-");
//            }
//            if (txtDisplay.getText().equals("0")) {
//                txtDisplay.setText("");
//            }
            txtDisplay.setText(txtDisplay.getText() + str);
        }
    }

    public void calculator() {
        if (operation.equalsIgnoreCase("add")) {
            result = result + getNumber();
        } else if (operation.equalsIgnoreCase("sub")) {
            result = result - getNumber();
        } else if (operation.equalsIgnoreCase("multi")) {
            result = result * getNumber();
        } else if (operation.equalsIgnoreCase("div")) {
            if (getNumber() == 0) {
                JOptionPane.showMessageDialog(this, "Khong duoc chia cho 0");
            } else {
                result = result / getNumber();
            }
        } else {
            result = getNumber();
        }
        setTextFormat(result);       
        check = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtDisplay = new javax.swing.JTextField();
        btnMC = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnMAdd = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnMSub = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btnInverse = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnSwap = new javax.swing.JButton();
        labelOperator = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnMStore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Calculator");

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("0");
        txtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayActionPerformed(evt);
            }
        });

        btnMC.setBackground(new java.awt.Color(255, 255, 0));
        btnMC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMC.setText("MC");
        btnMC.setEnabled(false);
        btnMC.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMC.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });

        btnNum7.setBackground(new java.awt.Color(255, 102, 153));
        btnNum7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum7.setText("7");
        btnNum7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum7.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum7ActionPerformed(evt);
            }
        });

        btnNum4.setBackground(new java.awt.Color(255, 102, 153));
        btnNum4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum4.setText("4");
        btnNum4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum4.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum4ActionPerformed(evt);
            }
        });

        btnNum1.setBackground(new java.awt.Color(255, 102, 153));
        btnNum1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum1.setText("1");
        btnNum1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum1.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum1ActionPerformed(evt);
            }
        });

        btnNum0.setBackground(new java.awt.Color(255, 102, 153));
        btnNum0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum0.setText("0");
        btnNum0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum0.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum0ActionPerformed(evt);
            }
        });

        btnMR.setBackground(new java.awt.Color(255, 255, 0));
        btnMR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMR.setText("MR");
        btnMR.setEnabled(false);
        btnMR.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMR.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });

        btnNum8.setBackground(new java.awt.Color(255, 102, 153));
        btnNum8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum8.setText("8");
        btnNum8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum8.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum8ActionPerformed(evt);
            }
        });

        btnNum5.setBackground(new java.awt.Color(255, 102, 153));
        btnNum5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum5.setText("5");
        btnNum5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum5.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum5ActionPerformed(evt);
            }
        });

        btnNum2.setBackground(new java.awt.Color(255, 102, 153));
        btnNum2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum2.setText("2");
        btnNum2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum2.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum2ActionPerformed(evt);
            }
        });

        btnDot.setBackground(new java.awt.Color(51, 204, 0));
        btnDot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDot.setText(".");
        btnDot.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDot.setPreferredSize(new java.awt.Dimension(40, 40));
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnMAdd.setBackground(new java.awt.Color(255, 255, 0));
        btnMAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMAdd.setText("M+");
        btnMAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMAdd.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAddActionPerformed(evt);
            }
        });

        btnNum9.setBackground(new java.awt.Color(255, 102, 153));
        btnNum9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum9.setText("9");
        btnNum9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum9.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum9ActionPerformed(evt);
            }
        });

        btnNum6.setBackground(new java.awt.Color(255, 102, 153));
        btnNum6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum6.setText("6");
        btnNum6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum6.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum6ActionPerformed(evt);
            }
        });

        btnNum3.setBackground(new java.awt.Color(255, 102, 153));
        btnNum3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNum3.setText("3");
        btnNum3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNum3.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum3ActionPerformed(evt);
            }
        });

        btnMSub.setBackground(new java.awt.Color(255, 255, 0));
        btnMSub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMSub.setText("M-");
        btnMSub.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMSub.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSubActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(51, 204, 0));
        btnDiv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDiv.setText("/");
        btnDiv.setActionCommand("Div");
        btnDiv.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDiv.setPreferredSize(new java.awt.Dimension(40, 40));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnMulti.setBackground(new java.awt.Color(51, 204, 0));
        btnMulti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMulti.setText("x");
        btnMulti.setActionCommand("Multi");
        btnMulti.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMulti.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnSub.setBackground(new java.awt.Color(51, 204, 0));
        btnSub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSub.setText("-");
        btnSub.setActionCommand("Sub");
        btnSub.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSub.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(51, 204, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setActionCommand("Add");
        btnAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnAdd.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSqrt.setBackground(new java.awt.Color(51, 204, 0));
        btnSqrt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSqrt.setText("√");
        btnSqrt.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSqrt.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        btnPercent.setBackground(new java.awt.Color(51, 204, 0));
        btnPercent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPercent.setText("%");
        btnPercent.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnPercent.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });

        btnInverse.setBackground(new java.awt.Color(51, 204, 0));
        btnInverse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInverse.setText("1/x");
        btnInverse.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnInverse.setPreferredSize(new java.awt.Dimension(40, 40));
        btnInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInverseActionPerformed(evt);
            }
        });

        btnEqual.setBackground(new java.awt.Color(51, 204, 0));
        btnEqual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEqual.setText("=");
        btnEqual.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnEqual.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnSwap.setBackground(new java.awt.Color(51, 204, 0));
        btnSwap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSwap.setText("+/-");
        btnSwap.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSwap.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwapActionPerformed(evt);
            }
        });

        labelOperator.setMaximumSize(new java.awt.Dimension(40, 23));
        labelOperator.setMinimumSize(new java.awt.Dimension(40, 23));
        labelOperator.setPreferredSize(new java.awt.Dimension(40, 23));

        btnDelete.setBackground(new java.awt.Color(255, 255, 0));
        btnDelete.setText("←");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnMStore.setBackground(new java.awt.Color(255, 255, 0));
        btnMStore.setText("MS");
        btnMStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMStoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnInverse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSwap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMStore, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnClear)
                        .addComponent(btnMStore)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInverse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSwap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        setTextFormat(m.getM());
        check = true;
    }//GEN-LAST:event_btnMRActionPerformed

    private void btnMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAddActionPerformed
        if (m != null) {
            m.setM(m.getM() + getNumber());
            
        } else {
            m = new Memory(getNumber());
            btnMC.setEnabled(true);
            btnMR.setEnabled(true);
        }
        check = true;
    }//GEN-LAST:event_btnMAddActionPerformed

    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed
        mClear();
    }//GEN-LAST:event_btnMCActionPerformed

    private void btnMSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSubActionPerformed
        if (m != null) {
            m.setM(m.getM() - getNumber());
        } else {
            m = new Memory(0 - getNumber());
            btnMC.setEnabled(true);
            btnMR.setEnabled(true);
        }
        check = true;
    }//GEN-LAST:event_btnMSubActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
//        if (getNumber() < 0) {
//            JOptionPane.showMessageDialog(this, "Can lam sao duoc so am :|");
//            return;
//        }
        setTextFormat(Math.sqrt(getNumber()));
        check = true;
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentActionPerformed
        setTextFormat(getNumber() / 100);
        check = true;
    }//GEN-LAST:event_btnPercentActionPerformed

    private void btnInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInverseActionPerformed
        if (getNumber() == 0) {
            JOptionPane.showMessageDialog(this, "no inverse given 0");
        } else {
            setTextFormat(1 / getNumber());
        }
        check = true;
    }//GEN-LAST:event_btnInverseActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        calculator();
        setTextFormat(result);
        operation = "";
        check = true;
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        if (check) {
            operation = "div";
            return;
        }
        calculator();
        operation = "div";
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        if (check) {
            operation = "multi";
            return;
        }
        calculator();
        operation = "multi";
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        if (check) {
            operation = "sub";
            return;
        }
        calculator();
        operation = "sub";
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (check) {
            operation = "add";
            return;
        }
        calculator();
        operation = "add";
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwapActionPerformed
      //  if(!check){
        if (getNumber() <= 0) {
            txtDisplay.setText(txtDisplay.getText().replace("-", ""));
            
        } else {
            txtDisplay.setText("-" + txtDisplay.getText());
     //   }
        }
    }//GEN-LAST:event_btnSwapActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        if (!txtDisplay.getText().contains(".") && check == false) {
            txtDisplay.setText(txtDisplay.getText() + ".");
            
        }
        if (check == true) {
            txtDisplay.setText("0.");
            check = false;
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!check) {
            String str = txtDisplay.getText();
            String result = "0";
            if (str.length() > 1) {
                result = str.substring(0, str.length() - 1);
            }
            if (str.length() == 1) {
                result = "0";
                         
            }
//            if (str.startsWith("-") && str.length() == 2) {
//                result = "0";
//            }
            txtDisplay.setText(result);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtDisplay.setText("0");
       // mClear();
        result = 0;
        operation = "add";
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMStoreActionPerformed
        // TODO add your handling code here:
        m = new Memory(getNumber());
        btnMC.setEnabled(true);
        btnMR.setEnabled(true);
        check = true;
    }//GEN-LAST:event_btnMStoreActionPerformed

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayActionPerformed

    private void btnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum1ActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_btnNum1ActionPerformed

    private void btnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum0ActionPerformed
        if (!txtDisplay.getText().equals("0")) {
            actionPerformed(evt);
       }
    }//GEN-LAST:event_btnNum0ActionPerformed

    private void btnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum2ActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_btnNum2ActionPerformed

    private void btnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum3ActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_btnNum3ActionPerformed

    private void btnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum4ActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_btnNum4ActionPerformed

    private void btnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum5ActionPerformed

        actionPerformed(evt);
    }//GEN-LAST:event_btnNum5ActionPerformed

    private void btnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum6ActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_btnNum6ActionPerformed

    private void btnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum7ActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_btnNum7ActionPerformed

    private void btnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum8ActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_btnNum8ActionPerformed

    private void btnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum9ActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_btnNum9ActionPerformed

    private void mClear() {
        btnMC.setEnabled(false);
        btnMR.setEnabled(false);
        m = null;
        check = true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    public javax.swing.JButton btnEqual;
    private javax.swing.JButton btnInverse;
    private javax.swing.JButton btnMAdd;
    public javax.swing.JButton btnMC;
    public javax.swing.JButton btnMR;
    private javax.swing.JButton btnMStore;
    private javax.swing.JButton btnMSub;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnSwap;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel labelOperator;
    public static javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables

}
